In [70]:
import pandas as pd

In [71]:
df = pd.read_csv('Melbourne_housing_FULL.csv')

In [72]:
df.head(5)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [73]:
del df['Address']
del df['Method']
del df['SellerG']
del df['Date']
del df['Postcode']
del df['Lattitude']
del df['Longtitude']
del df['Regionname']
del df['Propertycount']

In [74]:
df.head()

,Suburb,Rooms,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea
0,Abbotsford,2,h,NaN,2.5,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council
1,Abbotsford,2,h,1480000.0,2.5,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council
2,Abbotsford,2,h,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council
3,Abbotsford,3,u,NaN,2.5,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council
4,Abbotsford,3,h,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Suburb        34857 non-null  object
 1   Rooms         34857 non-null  int64
 2   Type          34857 non-null  object
 3   Price         27247 non-null  float64
 4   Distance      34856 non-null  float64
 5   Bedroom2      26640 non-null  float64
 6   Bathroom      26631 non-null  float64
 7   Car           26129 non-null  float64
 8   Landsize      23047 non-null  float64
 9   BuildingArea  13742 non-null  float64
 10  YearBuilt     15551 non-null  float64
 11  CouncilArea   34854 non-null  object
dtypes: float64(8), int64(1), object(3)
memory usage: 3.2+ MB

In [76]:
df.dropna(axis=0, how='any', inplace=True)

In [77]:
features_df = pd.get_dummies(df, columns=['Suburb', 'CouncilArea', 'Type'])

In [78]:
df.head()

,Suburb,Rooms,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea
2,Abbotsford,2,h,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council
4,Abbotsford,3,h,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council
6,Abbotsford,4,h,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra City Council
11,Abbotsford,3,h,1876000.0,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,Yarra City Council
14,Abbotsford,2,h,1636000.0,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,Yarra City Council

In [79]:
del features_df['Price']

In [80]:
features_df.head()

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Suburb_Abbotsford,Suburb_Aberfeldie,...,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Type_h,Type_t,Type_u
2,2,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,1,0,...,0,0,0,0,0,1,0,1,0,0
4,3,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,1,0,...,0,0,0,0,0,1,0,1,0,0
6,4,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,1,0,...,0,0,0,0,0,1,0,1,0,0
11,3,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,1,0,...,0,0,0,0,0,1,0,1,0,0
14,2,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,1,0,...,0,0,0,0,0,1,0,1,0,0

In [81]:
X = features_df.values
y = df['Price'].values

In [82]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\chamod\anaconda3\lib\site-packages (1.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\chamod\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\chamod\anaconda3\lib\site-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: joblib>=1.1.1 in c:\users\chamod\anaconda3\lib\site-packages (from scikit-learn) (1.1.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\chamod\anaconda3\lib\site-packages (from scikit-learn) (1.10.0)
Note: you may need to restart the kernel to use updated packages.

In [83]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [84]:
from sklearn import ensemble

model = ensemble.GradientBoostingRegressor(
    n_estimators=150,
    learning_rate=0.1,
    max_depth=30,
    min_samples_split=4,
    min_samples_leaf=6,
    max_features=0.6,
    loss='huber'
)

In [85]:
model.fit(X_train, y_train)

GradientBoostingRegressor(loss='huber', max_depth=30, max_features=0.6,
                          min_samples_leaf=6, min_samples_split=4,
                          n_estimators=150)

In [87]:
import joblib

joblib.dump(model, 'house_trained_model.pkl')

['house_trained_model.pkl']

In [89]:
from sklearn.metrics import mean_absolute_error

mse = mean_absolute_error(y_train, model.predict(X_train))
print("Training Set Mean Absolute Error: %.2f" % mse)

Training Set Mean Absolute Error: 29807.79

In [90]:
mse = mean_absolute_error(y_test, model.predict(X_test))
print ("Test Set Mean Absolute Error: %.2f" % mse)

Test Set Mean Absolute Error: 163403.03